name: Update Fork

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: main
        submodules: recursive

    - name: Set up Git
      run: |
        git config --global user.email "adamw97@vt.edu"
        git config --global user.name "Adam Wilborn"
        
    - name: Fetch Upstream
      run: |
        git remote add upstream https://github.com/UberGuidoZ/Flipper.git
        git fetch upstream
        git rebase upstream/main

    - name: Update Submodules
      run: |
        git submodule update --remote --recursive

    - name: Push Changes
      run: |
        git pull origin main
        git push origin main
